Kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  cert-manager.io/cluster-issuer: letsencrypt
  kubernetes.io/ingress.class: nginx
  name: some-name
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: gl.com
    http:
      paths:
      - backend:
          serviceName: some-service-name
          servicePort: "80"
  - host: google.com
    http:
      paths:
      - backend:
          serviceName: some-service-name
          servicePort: "80"
  tls:
  - hosts:
    - google.com
    secretName: some-name
